
-- OneCentrum Web Push setup
-- Run this in Supabase SQL Editor.

create table if not exists public.push_subscriptions (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    endpoint text not null unique,
    subscription jsonb not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists "users can manage own push subscriptions"
on public.push_subscriptions;

create policy "users can manage own push subscriptions"
on public.push_subscriptions
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

grant select, insert, update, delete
on public.push_subscriptions
to authenticated;

create index if not exists push_subscriptions_user_id_idx
on public.push_subscriptions(user_id);
